version: '3.8'

services:
  # PostgreSQL Container Configuration
  postgres:
    image: postgres:16          # latest stable version
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: springboot             # database to create
      POSTGRES_USER: nirmala              # application user
      POSTGRES_PASSWORD: nirmala@123      # user password
      TZ: Asia/Kolkata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
