server:
  port: 9897

spring:
  application:
    name: spring-boot-validation

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: ${POSTGRES_USER:nirmala}
    password: ${POSTGRES_PASSWORD:nirmala@123}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /documentation
  api-docs:
    path: /api-docs

openapi:
  title: 🚀 Spring Boot With SQL DB
  description: Spring Boot with SQL DB using Spring Data JPA and PostgreSQL Database
  version: 1.0.0
  contact:
    name: Nirmala Sahu
    email: nirmalakumarsahu7@gmail.com
    url: https://nirmalakumarsahu.in
  servers:
    - name: dev
      url: http://localhost:9897
      description: Local Development URL